name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Update CocoaPods repo
        run: |
          pod repo update
        working-directory: ios

      - name: Decode Provisioning Profile and Certificate
        run: |
          echo "Development Mobile Provision: ${DEVELOPMENT_MOBILEPROVISION:0:10}..."  # Outputs first 10 chars for sanity check
          echo "iOS Development Cert: ${IOS_DEVELOPMENT_CERT:0:10}..."

          echo "$DEVELOPMENT_MOBILEPROVISION" | base64 --decode --output ./ios/Runner/DoMa_Development.mobileprovision
          echo "$IOS_DEVELOPMENT_CERT" | base64 --decode --output ./ios/Runner/ios_development.cer

          # List files in the directory for debugging
          echo "Listing files in ./ios/Runner"
          ls -la ./ios/Runner

          # Import the certificate without using keychain
          echo "Importing certificate without keychain..."
          security import ./ios/Runner/ios_development.cer -T /usr/bin/codesign || echo "Certificate import failed"

      - name: Build iOS Release
        run: flutter build ios --release

      - name: Move Runner.app to Payload
        run: |
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
        working-directory: .

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
